version: '3.7'
services:
    solr:
        image: solr:latest
        ports:
            - "8983:8983"
        volumes:
            - data:/var/solr
        command:
            - solr-demo
volumes:
    data:

